#!/usr/bin/env bash
selectedNode="${@: -1}"

executionplane-info "EXECUTING INFOMETIS REMOVE"

.solution run stop . $selectedNode

.solution run shutdown . $selectedNode

.solution deploy down . $selectedNode
