#!/usr/bin/env bash

prefix="vcw_module_hkvb_traefik__$1"
prefix="vcw_module_hkvb_traefik__$1"

if [[ "vcw_module_hkvb_traefik__traefik_config_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_traefik__traefik_config_volume
fi

if [[ "vcw_module_hkvb_traefik__traefik_config_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_traefik__traefik_config_volume:/etc/traefik ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/traefik/_module/volumes/traefik_config_volume/* /etc/traefik
fi
