#!/usr/bin/env bash

executionplane --silent docker volume create hkvb_traefik__metrics_monitor_heartbeat_config
	
executionplane --silent docker volume create hkvb_traefik__metrics_monitor_heartbeat_data_volume
	
executionplane --silent docker volume create hkvb_traefik__metrics_monitor_heartbeat_monitors_volume
	
executionplane --silent docker volume create hkvb_traefik__traefik_traefik_config_volume
	

executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_traefik__metrics_monitor_heartbeat_config:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/traefik/_solution/_configuration/volumes/metrics_monitor_heartbeat_config/* /vcw/pwd


executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_traefik__metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/traefik/_solution/_configuration/volumes/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d


executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_traefik__traefik_traefik_config_volume:/etc/traefik ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/traefik/_solution/_configuration/volumes/traefik_traefik_config_volume/* /etc/traefik

