## traefik.yml
entrypoints:
  conteco:
    address: ":80"
  traefik:
    address: ":8080"

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    watch: true
    swarmMode: true
    exposedByDefault: false
    network: ${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay

# API and dashboard configuration
api:
  insecure: true
